#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GENERAL_BACKUP_ROOT="${BACKUP_ROOT:-${SCRIPT_DIR}/../backups}"
DATABASE_BACKUP_ROOT="${BACKUP_DATABASE_ROOT:-${GENERAL_BACKUP_ROOT}/database}"
DATABASE_KEEP_ARCHIVES="${KEEP_DATABASE_ARCHIVES:-${KEEP_ARCHIVES:-14}}"

BACKUP_SKIP_DB=0 \
BACKUP_INCLUDE_STORAGE=0 \
BACKUP_ROOT="${DATABASE_BACKUP_ROOT}" \
BACKUP_ARCHIVE_SUFFIX="-database" \
LATEST_POINTER_PATH="${DATABASE_BACKUP_ROOT}/.latest-successful-database-archive" \
KEEP_ARCHIVES="${DATABASE_KEEP_ARCHIVES}" \
/bin/bash "${SCRIPT_DIR}/backup.sh"
