#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GENERAL_BACKUP_ROOT="${BACKUP_ROOT:-${SCRIPT_DIR}/../backups}"
STORAGE_BACKUP_ROOT="${BACKUP_STORAGE_ROOT:-${GENERAL_BACKUP_ROOT}/storage}"
STORAGE_KEEP_ARCHIVES="${KEEP_STORAGE_ARCHIVES:-8}"

BACKUP_SKIP_DB=1 \
BACKUP_INCLUDE_STORAGE=1 \
BACKUP_ROOT="${STORAGE_BACKUP_ROOT}" \
BACKUP_ARCHIVE_SUFFIX="-storage" \
LATEST_POINTER_PATH="${STORAGE_BACKUP_ROOT}/.latest-successful-storage-archive" \
KEEP_ARCHIVES="${STORAGE_KEEP_ARCHIVES}" \
"${SCRIPT_DIR}/backup.sh"
