/**
 * Значки застосунку — Phosphor під старими іменами Lucide (REQ-275).
 *
 * ЧОМУ ІМЕНА ЛИШИЛИСЬ ВІД LUCIDE. 14.09.2026 CRM переїхала з Lucide на
 * Phosphor: 253 різні значки в 254 файлах. Перейменовувати кожен виклик —
 * тисячі рядків змін, а в Phosphor ще й збіги з іншими іменами (`Link`,
 * `Image`, `List`, `Table`). Тому файли міняють лише рядок імпорту, а
 * відповідність «старе ім'я → значок Phosphor» живе тут, в одному місці.
 * Хочеш інший значок для `Trash2` — міняєш рядок тут, і він зміниться всюди.
 *
 * НОВИЙ ЗНАЧОК бери з Phosphor під його власним іменем: додай рядок у список
 * нижче або імпортуй із `@phosphor-icons/react` напряму. Файл згенеровано
 * скриптом, але правити його руками — нормально.
 *
 * ДРІБНІ ЗНАЧКИ НА КРОК БІЛЬШІ — у index.css (Артем, 14.09.2026): лінія
 * Phosphor тоншала на 14–16 px, тож `h-3.5` малюється 16 px, `h-4` — 18.
 * `strokeWidth` від Lucide Phosphor ігнорує.
 *
 * ЧОМУ ТУТ РЕЕКСПОРТ, А НЕ ОБГОРТКА НА КОЖЕН ЗНАЧОК. Обгортка — це виклик на
 * рівні модуля, і збирач тоді тримає всі 229 значків разом у тому чанку, де
 * живе цей файл, тобто в стартовому: вхід виріс із меж 240 до 363 кБ gzip.
 * Реекспорт нічого не виконує, і кожен значок їде в чанк сторінки, яка його
 * бере. Обгорнуто лише кілька значків із рухом — вони дрібні.
 *
 * РУХ. Кільком значкам `appIcon` додає клас `icon-motion-*`: сам по собі він
 * нічого не робить, а в index.css оживає, коли курсор над кнопкою чи
 * посиланням, у якому значок стоїть, і вимикається при «зменшити рух».
 */
import { forwardRef } from "react";
import type { Icon, IconProps } from "@phosphor-icons/react";
import {
  AirplaneIcon as PhAirplaneIcon,
  AirplaneTakeoffIcon as PhAirplaneTakeoffIcon,
  ArchiveIcon as PhArchiveIcon,
  ArrowBendUpLeftIcon as PhArrowBendUpLeftIcon,
  ArrowClockwiseIcon as PhArrowClockwiseIcon,
  ArrowCounterClockwiseIcon as PhArrowCounterClockwiseIcon,
  ArrowDownIcon as PhArrowDownIcon,
  ArrowLeftIcon as PhArrowLeftIcon,
  ArrowRightIcon as PhArrowRightIcon,
  ArrowSquareOutIcon as PhArrowSquareOutIcon,
  ArrowUUpLeftIcon as PhArrowUUpLeftIcon,
  ArrowUpIcon as PhArrowUpIcon,
  ArrowUpRightIcon as PhArrowUpRightIcon,
  ArrowsClockwiseIcon as PhArrowsClockwiseIcon,
  ArrowsDownUpIcon as PhArrowsDownUpIcon,
  ArrowsOutSimpleIcon as PhArrowsOutSimpleIcon,
  BankIcon as PhBankIcon,
  BellIcon as PhBellIcon,
  BellRingingIcon as PhBellRingingIcon,
  BellSlashIcon as PhBellSlashIcon,
  BinaryIcon as PhBinaryIcon,
  BookOpenIcon as PhBookOpenIcon,
  BoxArrowUpIcon as PhBoxArrowUpIcon,
  BracketsCurlyIcon as PhBracketsCurlyIcon,
  BriefcaseIcon as PhBriefcaseIcon,
  BugIcon as PhBugIcon,
  BuildingsIcon as PhBuildingsIcon,
  CakeIcon as PhCakeIcon,
  CalculatorIcon as PhCalculatorIcon,
  CalendarBlankIcon as PhCalendarBlankIcon,
  CalendarDotIcon as PhCalendarDotIcon,
  CalendarDotsIcon as PhCalendarDotsIcon,
  CalendarIcon as PhCalendarIcon,
  CalendarPlusIcon as PhCalendarPlusIcon,
  CalendarSlashIcon as PhCalendarSlashIcon,
  CameraIcon as PhCameraIcon,
  CarIcon as PhCarIcon,
  CaretDoubleDownIcon as PhCaretDoubleDownIcon,
  CaretDownIcon as PhCaretDownIcon,
  CaretLeftIcon as PhCaretLeftIcon,
  CaretRightIcon as PhCaretRightIcon,
  CaretUpDownIcon as PhCaretUpDownIcon,
  CaretUpIcon as PhCaretUpIcon,
  ChartBarIcon as PhChartBarIcon,
  ChatIcon as PhChatIcon,
  ChatsIcon as PhChatsIcon,
  CheckCircleIcon as PhCheckCircleIcon,
  CheckIcon as PhCheckIcon,
  ChecksIcon as PhChecksIcon,
  CircleDashedIcon as PhCircleDashedIcon,
  CircleIcon as PhCircleIcon,
  CircleNotchIcon as PhCircleNotchIcon,
  ClipboardTextIcon as PhClipboardTextIcon,
  ClockCounterClockwiseIcon as PhClockCounterClockwiseIcon,
  ClockIcon as PhClockIcon,
  CloudArrowUpIcon as PhCloudArrowUpIcon,
  CloudIcon as PhCloudIcon,
  CoffeeIcon as PhCoffeeIcon,
  CoinsIcon as PhCoinsIcon,
  CompassIcon as PhCompassIcon,
  ConfettiIcon as PhConfettiIcon,
  CopyIcon as PhCopyIcon,
  CreditCardIcon as PhCreditCardIcon,
  CubeIcon as PhCubeIcon,
  CurrencyCircleDollarIcon as PhCurrencyCircleDollarIcon,
  CurrencyDollarIcon as PhCurrencyDollarIcon,
  CursorClickIcon as PhCursorClickIcon,
  DatabaseIcon as PhDatabaseIcon,
  DevicesIcon as PhDevicesIcon,
  DotIcon as PhDotIcon,
  DotsSixVerticalIcon as PhDotsSixVerticalIcon,
  DotsThreeIcon as PhDotsThreeIcon,
  DotsThreeVerticalIcon as PhDotsThreeVerticalIcon,
  DownloadIcon as PhDownloadIcon,
  DownloadSimpleIcon as PhDownloadSimpleIcon,
  DropIcon as PhDropIcon,
  EnvelopeSimpleIcon as PhEnvelopeSimpleIcon,
  EyeIcon as PhEyeIcon,
  EyeSlashIcon as PhEyeSlashIcon,
  FactoryIcon as PhFactoryIcon,
  FileArrowDownIcon as PhFileArrowDownIcon,
  FilePlusIcon as PhFilePlusIcon,
  FileTextIcon as PhFileTextIcon,
  FileXlsIcon as PhFileXlsIcon,
  FilesIcon as PhFilesIcon,
  FlaskIcon as PhFlaskIcon,
  FloppyDiskIcon as PhFloppyDiskIcon,
  FlowArrowIcon as PhFlowArrowIcon,
  FolderOpenIcon as PhFolderOpenIcon,
  FolderPlusIcon as PhFolderPlusIcon,
  FunnelIcon as PhFunnelIcon,
  FunnelSimpleIcon as PhFunnelSimpleIcon,
  FunnelXIcon as PhFunnelXIcon,
  GaugeIcon as PhGaugeIcon,
  GearIcon as PhGearIcon,
  GearSixIcon as PhGearSixIcon,
  GiftIcon as PhGiftIcon,
  GitCommitIcon as PhGitCommitIcon,
  GitPullRequestIcon as PhGitPullRequestIcon,
  GlobeIcon as PhGlobeIcon,
  GraduationCapIcon as PhGraduationCapIcon,
  GridNineIcon as PhGridNineIcon,
  HammerIcon as PhHammerIcon,
  HandshakeIcon as PhHandshakeIcon,
  HardDriveIcon as PhHardDriveIcon,
  HardDrivesIcon as PhHardDrivesIcon,
  HourglassIcon as PhHourglassIcon,
  HouseIcon as PhHouseIcon,
  ImageBrokenIcon as PhImageBrokenIcon,
  ImageIcon as PhImageIcon,
  InfoIcon as PhInfoIcon,
  KanbanIcon as PhKanbanIcon,
  KeyIcon as PhKeyIcon,
  LaptopIcon as PhLaptopIcon,
  LayoutIcon as PhLayoutIcon,
  LightbulbIcon as PhLightbulbIcon,
  LightningIcon as PhLightningIcon,
  LinkBreakIcon as PhLinkBreakIcon,
  LinkIcon as PhLinkIcon,
  LinkSimpleBreakIcon as PhLinkSimpleBreakIcon,
  LinkSimpleIcon as PhLinkSimpleIcon,
  ListChecksIcon as PhListChecksIcon,
  ListIcon as PhListIcon,
  ListNumbersIcon as PhListNumbersIcon,
  LockIcon as PhLockIcon,
  LockOpenIcon as PhLockOpenIcon,
  MagicWandIcon as PhMagicWandIcon,
  MagnifyingGlassIcon as PhMagnifyingGlassIcon,
  MagnifyingGlassMinusIcon as PhMagnifyingGlassMinusIcon,
  MapPinIcon as PhMapPinIcon,
  MedalIcon as PhMedalIcon,
  MegaphoneIcon as PhMegaphoneIcon,
  MicrophoneIcon as PhMicrophoneIcon,
  MinusIcon as PhMinusIcon,
  MoneyIcon as PhMoneyIcon,
  MonitorIcon as PhMonitorIcon,
  MoonIcon as PhMoonIcon,
  NewspaperIcon as PhNewspaperIcon,
  NoteIcon as PhNoteIcon,
  PackageIcon as PhPackageIcon,
  PaletteIcon as PhPaletteIcon,
  PaperPlaneTiltIcon as PhPaperPlaneTiltIcon,
  PaperclipIcon as PhPaperclipIcon,
  PathIcon as PhPathIcon,
  PauseIcon as PhPauseIcon,
  PencilIcon as PhPencilIcon,
  PencilLineIcon as PhPencilLineIcon,
  PencilSimpleIcon as PhPencilSimpleIcon,
  PercentIcon as PhPercentIcon,
  PhoneCallIcon as PhPhoneCallIcon,
  PhoneIcon as PhPhoneIcon,
  PiggyBankIcon as PhPiggyBankIcon,
  PlayCircleIcon as PhPlayCircleIcon,
  PlayIcon as PhPlayIcon,
  PlugIcon as PhPlugIcon,
  PlugsConnectedIcon as PhPlugsConnectedIcon,
  PlusCircleIcon as PhPlusCircleIcon,
  PlusIcon as PhPlusIcon,
  PresentationChartIcon as PhPresentationChartIcon,
  PresentationIcon as PhPresentationIcon,
  PrinterIcon as PhPrinterIcon,
  ProhibitIcon as PhProhibitIcon,
  PulseIcon as PhPulseIcon,
  PushPinIcon as PhPushPinIcon,
  PushPinSlashIcon as PhPushPinSlashIcon,
  QuestionIcon as PhQuestionIcon,
  RadioButtonIcon as PhRadioButtonIcon,
  ReceiptIcon as PhReceiptIcon,
  RepeatIcon as PhRepeatIcon,
  RobotIcon as PhRobotIcon,
  RocketIcon as PhRocketIcon,
  RowsIcon as PhRowsIcon,
  RulerIcon as PhRulerIcon,
  ScanIcon as PhScanIcon,
  ScissorsIcon as PhScissorsIcon,
  ScrollIcon as PhScrollIcon,
  SealCheckIcon as PhSealCheckIcon,
  ShieldCheckIcon as PhShieldCheckIcon,
  ShieldWarningIcon as PhShieldWarningIcon,
  ShoppingCartIcon as PhShoppingCartIcon,
  SidebarSimpleIcon as PhSidebarSimpleIcon,
  SignOutIcon as PhSignOutIcon,
  SignatureIcon as PhSignatureIcon,
  SignpostIcon as PhSignpostIcon,
  SlidersHorizontalIcon as PhSlidersHorizontalIcon,
  SmileyIcon as PhSmileyIcon,
  SparkleIcon as PhSparkleIcon,
  SpeakerHighIcon as PhSpeakerHighIcon,
  SprayBottleIcon as PhSprayBottleIcon,
  SquareIcon as PhSquareIcon,
  SquaresFourIcon as PhSquaresFourIcon,
  StackIcon as PhStackIcon,
  StackSimpleIcon as PhStackSimpleIcon,
  StarIcon as PhStarIcon,
  StorefrontIcon as PhStorefrontIcon,
  SunIcon as PhSunIcon,
  SwatchesIcon as PhSwatchesIcon,
  TShirtIcon as PhTShirtIcon,
  TableIcon as PhTableIcon,
  TagIcon as PhTagIcon,
  TargetIcon as PhTargetIcon,
  TextBIcon as PhTextBIcon,
  TextHTwoIcon as PhTextHTwoIcon,
  TextItalicIcon as PhTextItalicIcon,
  TextUnderlineIcon as PhTextUnderlineIcon,
  ThermometerIcon as PhThermometerIcon,
  ThumbsDownIcon as PhThumbsDownIcon,
  ThumbsUpIcon as PhThumbsUpIcon,
  TimerIcon as PhTimerIcon,
  TrashIcon as PhTrashIcon,
  TrayIcon as PhTrayIcon,
  TreeStructureIcon as PhTreeStructureIcon,
  TrendDownIcon as PhTrendDownIcon,
  TrendUpIcon as PhTrendUpIcon,
  TruckIcon as PhTruckIcon,
  UploadIcon as PhUploadIcon,
  UserCheckIcon as PhUserCheckIcon,
  UserIcon as PhUserIcon,
  UserMinusIcon as PhUserMinusIcon,
  UserPlusIcon as PhUserPlusIcon,
  UsersIcon as PhUsersIcon,
  WalletIcon as PhWalletIcon,
  WarningCircleIcon as PhWarningCircleIcon,
  WarningIcon as PhWarningIcon,
  WebhooksLogoIcon as PhWebhooksLogoIcon,
  WifiHighIcon as PhWifiHighIcon,
  WrenchIcon as PhWrenchIcon,
  XCircleIcon as PhXCircleIcon,
  XIcon as PhXIcon,
} from "@phosphor-icons/react";

import { cn } from "@/lib/utils";

/** Тип компонента значка — замість `LucideIcon`. */
export type AppIcon = Icon;

function withMotion(Base: Icon, motionClass: string): Icon {
  return forwardRef<SVGSVGElement, IconProps>(function MotionIcon({ className, ...props }, ref) {
    return <Base ref={ref} {...props} className={cn(motionClass, className)} />;
  });
}

export {
  PhPulseIcon as Activity,
  PhWarningCircleIcon as AlertCircle,
  PhWarningIcon as AlertTriangle,
  PhArchiveIcon as Archive,
  PhBoxArrowUpIcon as ArchiveRestore,
  PhArrowDownIcon as ArrowDown,
  PhArrowLeftIcon as ArrowLeft,
  PhArrowRightIcon as ArrowRight,
  PhArrowUpIcon as ArrowUp,
  PhArrowsDownUpIcon as ArrowUpDown,
  PhArrowUpRightIcon as ArrowUpRight,
  PhMedalIcon as Award,
  PhSealCheckIcon as BadgeCheck,
  PhCurrencyCircleDollarIcon as BadgeDollarSign,
  PhMoneyIcon as Banknote,
  PhChartBarIcon as BarChart3,
  PhBellSlashIcon as BellOff,
  PhBinaryIcon as Binary,
  PhTextBIcon as Bold,
  PhBookOpenIcon as BookOpen,
  PhRobotIcon as Bot,
  PhCubeIcon as Box,
  PhStackIcon as Boxes,
  PhBracketsCurlyIcon as Braces,
  PhBriefcaseIcon as Briefcase,
  PhBriefcaseIcon as BriefcaseBusiness,
  PhBugIcon as Bug,
  PhBuildingsIcon as Building2,
  PhCakeIcon as Cake,
  PhCalculatorIcon as Calculator,
  PhCalendarIcon as Calendar,
  PhCalendarDotIcon as CalendarClock,
  PhCalendarDotsIcon as CalendarDays,
  PhCalendarBlankIcon as CalendarIcon,
  PhCalendarSlashIcon as CalendarOff,
  PhCalendarPlusIcon as CalendarPlus,
  PhCalendarIcon as CalendarRange,
  PhCameraIcon as Camera,
  PhCarIcon as Car,
  PhCheckIcon as Check,
  PhChecksIcon as CheckCheck,
  PhCheckCircleIcon as CheckCircle2,
  PhCaretDownIcon as ChevronDown,
  PhCaretLeftIcon as ChevronLeft,
  PhCaretRightIcon as ChevronRight,
  PhCaretUpIcon as ChevronUp,
  PhCaretDoubleDownIcon as ChevronsDown,
  PhCaretUpDownIcon as ChevronsUpDown,
  PhCircleIcon as Circle,
  PhWarningCircleIcon as CircleAlert,
  PhCircleDashedIcon as CircleDashed,
  PhRadioButtonIcon as CircleDot,
  PhQuestionIcon as CircleHelp,
  PhProhibitIcon as CircleSlash,
  PhClipboardTextIcon as ClipboardCheck,
  PhClockIcon as Clock,
  PhClockIcon as Clock3,
  PhCloudIcon as Cloud,
  PhCloudArrowUpIcon as CloudUpload,
  PhCoffeeIcon as Coffee,
  PhCoinsIcon as Coins,
  PhCompassIcon as Compass,
  PhArrowBendUpLeftIcon as CornerUpLeft,
  PhCreditCardIcon as CreditCard,
  PhDatabaseIcon as Database,
  PhCurrencyDollarIcon as DollarSign,
  PhDotIcon as Dot,
  PhDownloadIcon as Download,
  PhDropIcon as Droplet,
  PhPencilSimpleIcon as Edit2,
  PhPencilLineIcon as Edit3,
  PhArrowSquareOutIcon as ExternalLink,
  PhEyeIcon as Eye,
  PhEyeSlashIcon as EyeOff,
  PhFactoryIcon as Factory,
  PhPresentationChartIcon as FileBarChart,
  PhFileArrowDownIcon as FileDown,
  PhFilePlusIcon as FilePlus2,
  PhSignatureIcon as FileSignature,
  PhFileXlsIcon as FileSpreadsheet,
  PhFileTextIcon as FileText,
  PhFilesIcon as Files,
  PhFunnelIcon as Filter,
  PhFunnelXIcon as FilterX,
  PhFlaskIcon as FlaskConical,
  PhKanbanIcon as FolderKanban,
  PhFolderOpenIcon as FolderOpen,
  PhFolderPlusIcon as FolderPlus,
  PhTreeStructureIcon as FolderTree,
  PhGaugeIcon as Gauge,
  PhGiftIcon as Gift,
  PhGitCommitIcon as GitCommitVertical,
  PhGitPullRequestIcon as GitPullRequestArrow,
  PhGlobeIcon as Globe,
  PhGraduationCapIcon as GraduationCap,
  PhGridNineIcon as Grid3x3,
  PhDotsSixVerticalIcon as GripVertical,
  PhHammerIcon as Hammer,
  PhHandshakeIcon as Handshake,
  PhHardDriveIcon as HardDrive,
  PhTextHTwoIcon as Heading2,
  PhQuestionIcon as HelpCircle,
  PhClockCounterClockwiseIcon as History,
  PhHourglassIcon as Hourglass,
  PhHouseIcon as House,
  PhImageIcon as Image,
  PhDownloadSimpleIcon as ImageDown,
  PhImageIcon as ImageIcon,
  PhImageBrokenIcon as ImageOff,
  PhTrayIcon as Inbox,
  PhInfoIcon as Info,
  PhTextItalicIcon as Italic,
  PhKanbanIcon as KanbanSquare,
  PhKeyIcon as KeyRound,
  PhBankIcon as Landmark,
  PhLaptopIcon as Laptop,
  PhStackIcon as Layers,
  PhStackSimpleIcon as Layers3,
  PhSquaresFourIcon as LayoutGrid,
  PhLightbulbIcon as Lightbulb,
  PhLinkIcon as Link,
  PhLinkSimpleIcon as Link2,
  PhLinkSimpleBreakIcon as Link2Off,
  PhListIcon as List,
  PhListChecksIcon as ListChecks,
  PhFunnelSimpleIcon as ListFilter,
  PhListNumbersIcon as ListOrdered,
  PhListChecksIcon as ListTodo,
  PhCircleNotchIcon as Loader2,
  PhLockIcon as Lock,
  PhSignOutIcon as LogOut,
  PhEnvelopeSimpleIcon as Mail,
  PhMapPinIcon as MapPin,
  PhArrowsOutSimpleIcon as Maximize2,
  PhMegaphoneIcon as Megaphone,
  PhListIcon as Menu,
  PhChatIcon as MessageSquare,
  PhChatsIcon as MessagesSquare,
  PhMicrophoneIcon as Mic,
  PhMinusIcon as Minus,
  PhMonitorIcon as Monitor,
  PhDevicesIcon as MonitorSmartphone,
  PhMoonIcon as Moon,
  PhDotsThreeIcon as MoreHorizontal,
  PhDotsThreeVerticalIcon as MoreVertical,
  PhCursorClickIcon as MousePointerClick,
  PhNewspaperIcon as Newspaper,
  PhPackageIcon as Package,
  PhPackageIcon as PackageCheck,
  PhPackageIcon as PackageSearch,
  PhPaletteIcon as Palette,
  PhSidebarSimpleIcon as PanelLeftClose,
  PhSidebarSimpleIcon as PanelLeftOpen,
  PhLayoutIcon as PanelsTopLeft,
  PhPaperclipIcon as Paperclip,
  PhConfettiIcon as PartyPopper,
  PhPauseIcon as Pause,
  PhPencilIcon as Pencil,
  PhPencilLineIcon as PencilLine,
  PhPercentIcon as Percent,
  PhPhoneIcon as Phone,
  PhPhoneCallIcon as PhoneCall,
  PhPiggyBankIcon as PiggyBank,
  PhPushPinIcon as Pin,
  PhPushPinSlashIcon as PinOff,
  PhAirplaneIcon as Plane,
  PhAirplaneTakeoffIcon as PlaneTakeoff,
  PhPlayIcon as Play,
  PhPlayCircleIcon as PlayCircle,
  PhPlugIcon as Plug,
  PhPlugsConnectedIcon as PlugZap,
  PhPlusCircleIcon as PlusCircle,
  PhPresentationIcon as Presentation,
  PhPrinterIcon as Printer,
  PhReceiptIcon as Receipt,
  PhReceiptIcon as ReceiptText,
  PhArrowClockwiseIcon as Redo,
  PhRepeatIcon as Repeat,
  PhArrowBendUpLeftIcon as Reply,
  PhRocketIcon as Rocket,
  PhArrowCounterClockwiseIcon as RotateCcw,
  PhPathIcon as Route,
  PhRowsIcon as Rows3,
  PhRulerIcon as Ruler,
  PhFloppyDiskIcon as Save,
  PhScanIcon as Scan,
  PhScissorsIcon as Scissors,
  PhScrollIcon as ScrollText,
  PhMagnifyingGlassMinusIcon as SearchX,
  PhPaperPlaneTiltIcon as Send,
  PhHardDrivesIcon as ServerCrash,
  PhGearIcon as Settings,
  PhGearSixIcon as Settings2,
  PhShieldWarningIcon as ShieldAlert,
  PhShieldCheckIcon as ShieldCheck,
  PhTShirtIcon as Shirt,
  PhShoppingCartIcon as ShoppingCart,
  PhSignpostIcon as Signpost,
  PhSlidersHorizontalIcon as SlidersHorizontal,
  PhSmileyIcon as Smile,
  PhSmileyIcon as SmilePlus,
  PhSparkleIcon as Sparkle,
  PhSparkleIcon as Sparkles,
  PhSprayBottleIcon as SprayCan,
  PhSquareIcon as Square,
  PhStarIcon as Star,
  PhNoteIcon as StickyNote,
  PhStorefrontIcon as Store,
  PhSunIcon as Sun,
  PhSwatchesIcon as SwatchBook,
  PhTableIcon as Table2,
  PhTagIcon as Tag,
  PhTagIcon as Tags,
  PhTargetIcon as Target,
  PhThermometerIcon as Thermometer,
  PhThumbsDownIcon as ThumbsDown,
  PhThumbsUpIcon as ThumbsUp,
  PhTimerIcon as Timer,
  PhTimerIcon as TimerOff,
  PhClockCounterClockwiseIcon as TimerReset,
  PhTrendDownIcon as TrendingDown,
  PhTrendUpIcon as TrendingUp,
  PhTruckIcon as Truck,
  PhTextUnderlineIcon as Underline,
  PhArrowCounterClockwiseIcon as Undo,
  PhArrowUUpLeftIcon as Undo2,
  PhLinkBreakIcon as Unlink,
  PhLockOpenIcon as Unlock,
  PhUploadIcon as Upload,
  PhUserIcon as User,
  PhUserCheckIcon as UserCheck,
  PhUserMinusIcon as UserMinus,
  PhUserPlusIcon as UserPlus,
  PhUserIcon as UserRound,
  PhUserMinusIcon as UserX,
  PhUsersIcon as Users,
  PhSpeakerHighIcon as Volume2,
  PhWalletIcon as Wallet,
  PhMagicWandIcon as Wand2,
  PhWebhooksLogoIcon as Webhook,
  PhWifiHighIcon as Wifi,
  PhFlowArrowIcon as Workflow,
  PhWrenchIcon as Wrench,
  PhXIcon as X,
  PhXCircleIcon as XCircle,
  PhLightningIcon as Zap,
};

export const Bell = withMotion(PhBellIcon, "icon-motion-ring");
export const BellRing = withMotion(PhBellRingingIcon, "icon-motion-ring");
export const Copy = withMotion(PhCopyIcon, "icon-motion-lift");
export const Plus = withMotion(PhPlusIcon, "icon-motion-turn");
export const RefreshCw = withMotion(PhArrowsClockwiseIcon, "icon-motion-spin");
export const Search = withMotion(PhMagnifyingGlassIcon, "icon-motion-nudge");
export const Trash2 = withMotion(PhTrashIcon, "icon-motion-shake");
