/**
 * Значки застосунку — Phosphor під старими іменами Lucide (REQ-275).
 *
 * ЧОМУ ІМЕНА ЛИШИЛИСЬ ВІД LUCIDE. 14.09.2026 CRM переїхала з Lucide на
 * Phosphor: 253 різні значки в 254 файлах. Перейменовувати кожен виклик —
 * тисячі рядків змін, а в Phosphor ще й збіги з іншими іменами (`Link`,
 * `Image`, `List`, `Table`). Тому файли міняють лише рядок імпорту, а
 * відповідність «старе ім'я → значок Phosphor» живе тут, в одному місці.
 * Хочеш інший значок для `Trash2` — міняєш рядок тут, і він зміниться всюди.
 *
 * НОВИЙ ЗНАЧОК бери з Phosphor під його власним іменем: додай рядок у список
 * нижче або імпортуй із `@phosphor-icons/react` напряму. Файл згенеровано
 * скриптом, але правити його руками — нормально.
 *
 * ВАГА. За замовчуванням `regular`; `weight="fill"` на місці виклику дає
 * заповнений (так робить активний пункт сайдбару). `strokeWidth` від Lucide
 * Phosphor ігнорує — його заливані контури від нього не товщають.
 *
 * РУХ. Кілька значків загорнуто в `withMotion`: клас `icon-motion-*` сам по
 * собі нічого не робить, а в index.css оживає, коли курсор над кнопкою чи
 * посиланням, у якому значок стоїть, і вимикається при «зменшити рух».
 */
import { forwardRef } from "react";
import type { Icon, IconProps } from "@phosphor-icons/react";
import {
  AirplaneIcon,
  AirplaneTakeoffIcon,
  ArchiveIcon,
  ArrowBendUpLeftIcon,
  ArrowClockwiseIcon,
  ArrowCounterClockwiseIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowSquareOutIcon,
  ArrowUUpLeftIcon,
  ArrowUpIcon,
  ArrowUpRightIcon,
  ArrowsClockwiseIcon,
  ArrowsDownUpIcon,
  ArrowsOutSimpleIcon,
  BankIcon,
  BellIcon,
  BellRingingIcon,
  BellSlashIcon,
  BinaryIcon,
  BookOpenIcon,
  BoxArrowUpIcon,
  BracketsCurlyIcon,
  BriefcaseIcon,
  BugIcon,
  BuildingsIcon,
  CakeIcon,
  CalculatorIcon,
  CalendarBlankIcon,
  CalendarDotIcon,
  CalendarDotsIcon,
  CalendarIcon,
  CalendarPlusIcon,
  CalendarSlashIcon,
  CameraIcon,
  CarIcon,
  CaretDoubleDownIcon,
  CaretDownIcon,
  CaretLeftIcon,
  CaretRightIcon,
  CaretUpDownIcon,
  CaretUpIcon,
  ChartBarIcon,
  ChatIcon,
  ChatsIcon,
  CheckCircleIcon,
  CheckIcon,
  ChecksIcon,
  CircleDashedIcon,
  CircleIcon,
  CircleNotchIcon,
  ClipboardTextIcon,
  ClockCounterClockwiseIcon,
  ClockIcon,
  CloudArrowUpIcon,
  CloudIcon,
  CoffeeIcon,
  CoinsIcon,
  CompassIcon,
  ConfettiIcon,
  CopyIcon,
  CreditCardIcon,
  CubeIcon,
  CurrencyCircleDollarIcon,
  CurrencyDollarIcon,
  CursorClickIcon,
  DatabaseIcon,
  DevicesIcon,
  DotIcon,
  DotsSixVerticalIcon,
  DotsThreeIcon,
  DotsThreeVerticalIcon,
  DownloadIcon,
  DownloadSimpleIcon,
  DropIcon,
  EnvelopeSimpleIcon,
  EyeIcon,
  EyeSlashIcon,
  FactoryIcon,
  FileArrowDownIcon,
  FilePlusIcon,
  FileTextIcon,
  FileXlsIcon,
  FilesIcon,
  FlaskIcon,
  FloppyDiskIcon,
  FlowArrowIcon,
  FolderOpenIcon,
  FolderPlusIcon,
  FunnelIcon,
  FunnelSimpleIcon,
  FunnelXIcon,
  GaugeIcon,
  GearIcon,
  GearSixIcon,
  GiftIcon,
  GitCommitIcon,
  GitPullRequestIcon,
  GlobeIcon,
  GraduationCapIcon,
  GridNineIcon,
  HammerIcon,
  HandshakeIcon,
  HardDriveIcon,
  HardDrivesIcon,
  HourglassIcon,
  HouseIcon,
  ImageBrokenIcon,
  ImageIcon,
  InfoIcon,
  KanbanIcon,
  KeyIcon,
  LaptopIcon,
  LayoutIcon,
  LightbulbIcon,
  LightningIcon,
  LinkBreakIcon,
  LinkIcon,
  LinkSimpleBreakIcon,
  LinkSimpleIcon,
  ListChecksIcon,
  ListIcon,
  ListNumbersIcon,
  LockIcon,
  LockOpenIcon,
  MagicWandIcon,
  MagnifyingGlassIcon,
  MagnifyingGlassMinusIcon,
  MapPinIcon,
  MedalIcon,
  MegaphoneIcon,
  MicrophoneIcon,
  MinusIcon,
  MoneyIcon,
  MonitorIcon,
  MoonIcon,
  NewspaperIcon,
  NoteIcon,
  PackageIcon,
  PaletteIcon,
  PaperPlaneTiltIcon,
  PaperclipIcon,
  PathIcon,
  PauseIcon,
  PencilIcon,
  PencilLineIcon,
  PencilSimpleIcon,
  PercentIcon,
  PhoneCallIcon,
  PhoneIcon,
  PiggyBankIcon,
  PlayCircleIcon,
  PlayIcon,
  PlugIcon,
  PlugsConnectedIcon,
  PlusCircleIcon,
  PlusIcon,
  PresentationChartIcon,
  PresentationIcon,
  PrinterIcon,
  ProhibitIcon,
  PulseIcon,
  PushPinIcon,
  PushPinSlashIcon,
  QuestionIcon,
  RadioButtonIcon,
  ReceiptIcon,
  RepeatIcon,
  RobotIcon,
  RocketIcon,
  RowsIcon,
  RulerIcon,
  ScanIcon,
  ScissorsIcon,
  ScrollIcon,
  SealCheckIcon,
  ShieldCheckIcon,
  ShieldWarningIcon,
  ShoppingCartIcon,
  SidebarSimpleIcon,
  SignOutIcon,
  SignatureIcon,
  SignpostIcon,
  SlidersHorizontalIcon,
  SmileyIcon,
  SparkleIcon,
  SpeakerHighIcon,
  SprayBottleIcon,
  SquareIcon,
  SquaresFourIcon,
  StackIcon,
  StackSimpleIcon,
  StarIcon,
  StorefrontIcon,
  SunIcon,
  SwatchesIcon,
  TShirtIcon,
  TableIcon,
  TagIcon,
  TargetIcon,
  TextBIcon,
  TextHTwoIcon,
  TextItalicIcon,
  TextUnderlineIcon,
  ThermometerIcon,
  ThumbsDownIcon,
  ThumbsUpIcon,
  TimerIcon,
  TrashIcon,
  TrayIcon,
  TreeStructureIcon,
  TrendDownIcon,
  TrendUpIcon,
  TruckIcon,
  UploadIcon,
  UserCheckIcon,
  UserIcon,
  UserMinusIcon,
  UserPlusIcon,
  UsersIcon,
  WalletIcon,
  WarningCircleIcon,
  WarningIcon,
  WebhooksLogoIcon,
  WifiHighIcon,
  WrenchIcon,
  XCircleIcon,
  XIcon,
} from "@phosphor-icons/react";

import { cn } from "@/lib/utils";

/** Тип компонента значка — замість `LucideIcon`. */
export type AppIcon = Icon;

function withMotion(Base: Icon, motionClass: string): Icon {
  return forwardRef<SVGSVGElement, IconProps>(function MotionIcon({ className, ...props }, ref) {
    return <Base ref={ref} {...props} className={cn(motionClass, className)} />;
  });
}

export {
  PulseIcon as Activity,
  WarningCircleIcon as AlertCircle,
  WarningIcon as AlertTriangle,
  ArchiveIcon as Archive,
  BoxArrowUpIcon as ArchiveRestore,
  ArrowDownIcon as ArrowDown,
  ArrowLeftIcon as ArrowLeft,
  ArrowRightIcon as ArrowRight,
  ArrowUpIcon as ArrowUp,
  ArrowsDownUpIcon as ArrowUpDown,
  ArrowUpRightIcon as ArrowUpRight,
  MedalIcon as Award,
  SealCheckIcon as BadgeCheck,
  CurrencyCircleDollarIcon as BadgeDollarSign,
  MoneyIcon as Banknote,
  ChartBarIcon as BarChart3,
  BellSlashIcon as BellOff,
  BinaryIcon as Binary,
  TextBIcon as Bold,
  BookOpenIcon as BookOpen,
  RobotIcon as Bot,
  CubeIcon as Box,
  StackIcon as Boxes,
  BracketsCurlyIcon as Braces,
  BriefcaseIcon as Briefcase,
  BriefcaseIcon as BriefcaseBusiness,
  BugIcon as Bug,
  BuildingsIcon as Building2,
  CakeIcon as Cake,
  CalculatorIcon as Calculator,
  CalendarIcon as Calendar,
  CalendarDotIcon as CalendarClock,
  CalendarDotsIcon as CalendarDays,
  CalendarBlankIcon as CalendarIcon,
  CalendarSlashIcon as CalendarOff,
  CalendarPlusIcon as CalendarPlus,
  CalendarIcon as CalendarRange,
  CameraIcon as Camera,
  CarIcon as Car,
  CheckIcon as Check,
  ChecksIcon as CheckCheck,
  CheckCircleIcon as CheckCircle2,
  CaretDownIcon as ChevronDown,
  CaretLeftIcon as ChevronLeft,
  CaretRightIcon as ChevronRight,
  CaretUpIcon as ChevronUp,
  CaretDoubleDownIcon as ChevronsDown,
  CaretUpDownIcon as ChevronsUpDown,
  CircleIcon as Circle,
  WarningCircleIcon as CircleAlert,
  CircleDashedIcon as CircleDashed,
  RadioButtonIcon as CircleDot,
  QuestionIcon as CircleHelp,
  ProhibitIcon as CircleSlash,
  ClipboardTextIcon as ClipboardCheck,
  ClockIcon as Clock,
  ClockIcon as Clock3,
  CloudIcon as Cloud,
  CloudArrowUpIcon as CloudUpload,
  CoffeeIcon as Coffee,
  CoinsIcon as Coins,
  CompassIcon as Compass,
  ArrowBendUpLeftIcon as CornerUpLeft,
  CreditCardIcon as CreditCard,
  DatabaseIcon as Database,
  CurrencyDollarIcon as DollarSign,
  DotIcon as Dot,
  DownloadIcon as Download,
  DropIcon as Droplet,
  PencilSimpleIcon as Edit2,
  PencilLineIcon as Edit3,
  ArrowSquareOutIcon as ExternalLink,
  EyeIcon as Eye,
  EyeSlashIcon as EyeOff,
  FactoryIcon as Factory,
  PresentationChartIcon as FileBarChart,
  FileArrowDownIcon as FileDown,
  FilePlusIcon as FilePlus2,
  SignatureIcon as FileSignature,
  FileXlsIcon as FileSpreadsheet,
  FileTextIcon as FileText,
  FilesIcon as Files,
  FunnelIcon as Filter,
  FunnelXIcon as FilterX,
  FlaskIcon as FlaskConical,
  KanbanIcon as FolderKanban,
  FolderOpenIcon as FolderOpen,
  FolderPlusIcon as FolderPlus,
  TreeStructureIcon as FolderTree,
  GaugeIcon as Gauge,
  GiftIcon as Gift,
  GitCommitIcon as GitCommitVertical,
  GitPullRequestIcon as GitPullRequestArrow,
  GlobeIcon as Globe,
  GraduationCapIcon as GraduationCap,
  GridNineIcon as Grid3x3,
  DotsSixVerticalIcon as GripVertical,
  HammerIcon as Hammer,
  HandshakeIcon as Handshake,
  HardDriveIcon as HardDrive,
  TextHTwoIcon as Heading2,
  QuestionIcon as HelpCircle,
  ClockCounterClockwiseIcon as History,
  HourglassIcon as Hourglass,
  HouseIcon as House,
  ImageIcon as Image,
  DownloadSimpleIcon as ImageDown,
  ImageIcon as ImageIcon,
  ImageBrokenIcon as ImageOff,
  TrayIcon as Inbox,
  InfoIcon as Info,
  TextItalicIcon as Italic,
  KanbanIcon as KanbanSquare,
  KeyIcon as KeyRound,
  BankIcon as Landmark,
  LaptopIcon as Laptop,
  StackIcon as Layers,
  StackSimpleIcon as Layers3,
  SquaresFourIcon as LayoutGrid,
  LightbulbIcon as Lightbulb,
  LinkIcon as Link,
  LinkSimpleIcon as Link2,
  LinkSimpleBreakIcon as Link2Off,
  ListIcon as List,
  ListChecksIcon as ListChecks,
  FunnelSimpleIcon as ListFilter,
  ListNumbersIcon as ListOrdered,
  ListChecksIcon as ListTodo,
  CircleNotchIcon as Loader2,
  LockIcon as Lock,
  SignOutIcon as LogOut,
  EnvelopeSimpleIcon as Mail,
  MapPinIcon as MapPin,
  ArrowsOutSimpleIcon as Maximize2,
  MegaphoneIcon as Megaphone,
  ListIcon as Menu,
  ChatIcon as MessageSquare,
  ChatsIcon as MessagesSquare,
  MicrophoneIcon as Mic,
  MinusIcon as Minus,
  MonitorIcon as Monitor,
  DevicesIcon as MonitorSmartphone,
  MoonIcon as Moon,
  DotsThreeIcon as MoreHorizontal,
  DotsThreeVerticalIcon as MoreVertical,
  CursorClickIcon as MousePointerClick,
  NewspaperIcon as Newspaper,
  PackageIcon as Package,
  PackageIcon as PackageCheck,
  PackageIcon as PackageSearch,
  PaletteIcon as Palette,
  SidebarSimpleIcon as PanelLeftClose,
  SidebarSimpleIcon as PanelLeftOpen,
  LayoutIcon as PanelsTopLeft,
  PaperclipIcon as Paperclip,
  ConfettiIcon as PartyPopper,
  PauseIcon as Pause,
  PencilIcon as Pencil,
  PencilLineIcon as PencilLine,
  PercentIcon as Percent,
  PhoneIcon as Phone,
  PhoneCallIcon as PhoneCall,
  PiggyBankIcon as PiggyBank,
  PushPinIcon as Pin,
  PushPinSlashIcon as PinOff,
  AirplaneIcon as Plane,
  AirplaneTakeoffIcon as PlaneTakeoff,
  PlayIcon as Play,
  PlayCircleIcon as PlayCircle,
  PlugIcon as Plug,
  PlugsConnectedIcon as PlugZap,
  PlusCircleIcon as PlusCircle,
  PresentationIcon as Presentation,
  PrinterIcon as Printer,
  ReceiptIcon as Receipt,
  ReceiptIcon as ReceiptText,
  ArrowClockwiseIcon as Redo,
  RepeatIcon as Repeat,
  ArrowBendUpLeftIcon as Reply,
  RocketIcon as Rocket,
  ArrowCounterClockwiseIcon as RotateCcw,
  PathIcon as Route,
  RowsIcon as Rows3,
  RulerIcon as Ruler,
  FloppyDiskIcon as Save,
  ScanIcon as Scan,
  ScissorsIcon as Scissors,
  ScrollIcon as ScrollText,
  MagnifyingGlassMinusIcon as SearchX,
  PaperPlaneTiltIcon as Send,
  HardDrivesIcon as ServerCrash,
  GearIcon as Settings,
  GearSixIcon as Settings2,
  ShieldWarningIcon as ShieldAlert,
  ShieldCheckIcon as ShieldCheck,
  TShirtIcon as Shirt,
  ShoppingCartIcon as ShoppingCart,
  SignpostIcon as Signpost,
  SlidersHorizontalIcon as SlidersHorizontal,
  SmileyIcon as Smile,
  SmileyIcon as SmilePlus,
  SparkleIcon as Sparkle,
  SparkleIcon as Sparkles,
  SprayBottleIcon as SprayCan,
  SquareIcon as Square,
  StarIcon as Star,
  NoteIcon as StickyNote,
  StorefrontIcon as Store,
  SunIcon as Sun,
  SwatchesIcon as SwatchBook,
  TableIcon as Table2,
  TagIcon as Tag,
  TagIcon as Tags,
  TargetIcon as Target,
  ThermometerIcon as Thermometer,
  ThumbsDownIcon as ThumbsDown,
  ThumbsUpIcon as ThumbsUp,
  TimerIcon as Timer,
  TimerIcon as TimerOff,
  ClockCounterClockwiseIcon as TimerReset,
  TrendDownIcon as TrendingDown,
  TrendUpIcon as TrendingUp,
  TruckIcon as Truck,
  TextUnderlineIcon as Underline,
  ArrowCounterClockwiseIcon as Undo,
  ArrowUUpLeftIcon as Undo2,
  LinkBreakIcon as Unlink,
  LockOpenIcon as Unlock,
  UploadIcon as Upload,
  UserIcon as User,
  UserCheckIcon as UserCheck,
  UserMinusIcon as UserMinus,
  UserPlusIcon as UserPlus,
  UserIcon as UserRound,
  UserMinusIcon as UserX,
  UsersIcon as Users,
  SpeakerHighIcon as Volume2,
  WalletIcon as Wallet,
  MagicWandIcon as Wand2,
  WebhooksLogoIcon as Webhook,
  WifiHighIcon as Wifi,
  FlowArrowIcon as Workflow,
  WrenchIcon as Wrench,
  XIcon as X,
  XCircleIcon as XCircle,
  LightningIcon as Zap,
};

export const Bell = withMotion(BellIcon, "icon-motion-ring");
export const BellRing = withMotion(BellRingingIcon, "icon-motion-ring");
export const Copy = withMotion(CopyIcon, "icon-motion-lift");
export const Plus = withMotion(PlusIcon, "icon-motion-turn");
export const RefreshCw = withMotion(ArrowsClockwiseIcon, "icon-motion-spin");
export const Search = withMotion(MagnifyingGlassIcon, "icon-motion-nudge");
export const Trash2 = withMotion(TrashIcon, "icon-motion-shake");
